### ISSUE TITLE
GetxxxImplSingleton not what i want

### ISSUE THREAD

**Issue by LFernandoC** [alibaba/IOC-golang#144]
![image](https://user-images.githubusercontent.com/10249183/199715110-dfba64c4-2953-40b6-a64d-b72f4d5825ae.png)

**Comment by LaurenceLiZhixin** [comment]
I'll fix the problem right away, that's a bug that you have called "GetxxxIOCInterfaceSingleton" before calling "GetxxxSingleton", and framework cached the proxy.

**Comment by LaurenceLiZhixin** [comment]
@LFernandoC Please try latest tag v1.0.2
