### ISSUE TITLE
[proposal]: A few suggestions for container design

### ISSUE THREAD

**Issue by photowey** [alibaba/IOC-Golang#19]
```go
A few suggestions for design:
1.Register  `Bean` instance uses a unified entry.
2.Get `Bean` instance by a unified entry.
```

1.`#1`

```go
// now
// singleton register
func init() {
	singleton.RegisterStructDescriptor(&autowire.StructDescriptor{
	})
}

// prototype register
normal.RegisterStructDescriptor(&autowire.StructDescriptor{
	})
}
```

> Notes: `beanfactory` is just an alias, it can also be named "`ioc`" or "`beanMap`" etc.

```go
// optimization
// singleton register
func init() {
	beanfactory.Register(&autowire.StructDescriptor{
        Scope: "singleton"
	})
}

// prototype register
func init() {
    beanfactory.Register(&autowire.StructDescriptor{
            Scope: "prototype"
        })
    } 
}
```

2.`#2`	

```go
// now
// appInterface, err := singleton.GetImpl("App-App")


// optimization
// type.1
beanfactory.GetBean("App") // Names like App-App are repeated
beanfactory.GetImpl("App")
// -> App is the struct name


// type.2
beanfactory.GetBean(sdid.APP) 
// -> sdid: a const package generated by cli
// -> APP：struct-name or alias

// type.3
beanfactory.GetBean("Redis-Impl") // SDID: hard-code
beanfactory.GetBean(sdid.RedisImpl)
beanfactory.GetBean(sdid.RedisClient) // Redis-RedisClient


// generated code such as:
// package sdid
//
// const (
//     App string = "App" // App-App
//     RedisImpl string = "Redis-Impl"
//     RedisClient string = "Redis-Impl"
// )


// type.4
// add annotation, such as: component or beanname

// +ioc:autowired=true
// +ioc:autowired:scope=singleton
// +ioc:autowired:component=component-name // +ioc:autowired:beanname=bean-name
type App struct {}

beanfactory.GetBean(${component-name})
beanfactory.GetBean(${bean-name})
```

**Comment by LaurenceLiZhixin** [comment]
Thanks for your suggestions. @photowey 
1. Your suggest that add 'scope' into struct descriptor to describe autowire type. 
I think autowire type, like 'singleton', 'normal' is not concept of struct description information, but the way to **use** the struct. On the other hand, IOC-Golang follows the principle of who supplies who maintains. If developers extend autowire type, the register api should be provided in the extension. What's more, if we add 'scope', struct register with unsupported scope would cause error.
2. I think the most significant value point of your proposal is that, You restrict the 'get by api side' to import package containing dependent struct. Beyond that, I'm not sure what it means to break get API into two or three lines of code

**Comment by LaurenceLiZhixin** [comment]
Thanks for your suggestions, I'm sorry that didn't get your point before, now I got it.
I think your suggestions are very reasonable. 

Before, I thought the developer needs to avoid duplicating the implementation struct name, and  define the sdid with the short string `'${InterfaceName}-${StructName}'`, but now I think this design is not reasonable.

I agree with your design and prefer these implement methods:
1. Change SDID definition by interface class full name and implementation class full name: `"${InterfaceTypeFullName} - ${StructTypeFullName}"`,  for example "github.com/alibaba/ioc-golang/demo.MyInterface-github.com/alibaba/ioc-golang/demo/impl.MyImpl1"
2. In StructDescriptor, add a field "Alias" as an abbreviation of the full name of the type and interface. When using iocli to generate code, set the type alias by using the +ioc:autowire:alias = "MyInterface-MyImpl1" annotation. The developer needs to ensure that this alias is not globally duplicated, otherwise the framework will throw an error.

When get by api, user can call both
```go
impl, err := singleton.GetImpl("github.com/alibaba/ioc-golang/demo.MyInterface-github.com/alibaba/ioc-golang/demo/impl.MyImpl1")

impl, err := singleton.GetImpl("MyInterface-MyImpl1")
``` 
to get target impl object.

When inject by tag, user can set:

```go
import(
    github.com/alibaba/ioc-golang/demo
)

// +ioc:autowire=true
// +ioc:autowire:type=singleton
type App struct{
    MySubImpl demo.MyInterface `singleton:"github.com/alibaba/ioc-golang/demo/impl.MyImpl1"`
    MySubImpl demo.MyInterface `singleton:"MyImpl1"`
}
```
to inject target impl object.


I'm currently not prefer design of generating const block by iocli for two reasons. First, we can't require developers to import pkg containing struct implements, which is easy to create circular references. Second, I think iocli generated code needs to play the same role as user manual code registration SD, the two ways both can be selected, can be replaced by each other. Extra const values in iocli-generated code can cause trouble I think.

**Comment by LaurenceLiZhixin** [comment]
@photowey Do you have any time to implement this proposal?

**Comment by photowey** [comment]
Ok, it's my honour.

**Comment by photowey** [comment]
`Design ideas`

>Test case.
>
>[helloioc](https://github.com/photowey/helloioc)
>
>[autowire_config](https://github.com/photowey/IOC-Golang/blob/master/example/autowire_config)

1.Build  `SDID` by full pkg path.

2.Add `alias` annotation support.

3.Support dependency injection by alias and full name.

4.Improvement is needed.



`#1`

> The root of `autowire`(`autowire/boot`) hold a map of `SDID `alias mapping(`sdIDAliasMap`) named as `alias container`.
>
> -- -
>
> All aliases must be registered with the alias root container `sdIDAliasMap`, and duplication is not allowed, once duplication will trigger panic, so this design can also be considered.
>
> -- -
>
> parse `SDID`:
>
> 1.generate the full name with pkg path of the interface and struct.
>
> 2.If the interface has designed alias through annotation support, then we mapping the aliases to the full name.
>
> 3.When the bean is obtained from the ioc container, it will first look up the mapped full name from the alias registration, and then apply for the bean from the container, through the full name SDID.
>
> 4.Likewise, when dependency injection is required, the same approach is used to find the full name of the alias mapping, if necessary.
>
> -- -
>
> 5.The important thing is that with configuration injection, we need to map the ConfigXxx in the tag value to the full name: "github.com/alibaba/ioc-golang/extension/config.ConfigXxx"
>
> -- -
>
> 6.If a plain bean is registered with the container, that is, a bean that does not implement any interface, at this time, its SDID will be simplified to its full name of the package path instead of the `${interfaceName}-${structName}` or (`${structName}-${structName}`).
>
> ```go
> // By plain bean full name.
> singleton.GetImpl("github.com/photowey/helloioc/internal/order.Order")
> ```
>
> 



`#2`
>`StructDescriptor` add a property named as `Alias`
>
>```go
>type StructDescriptor struct {
>	Alias         string // alias of SDID
>}
>```
>
>> The developers can use aliases to replace full name that may be longer.
>
>```go
>// +ioc:autowire=true
>// +ioc:autowire:type=singleton
>// +ioc:autowire:alias=order
>
>type Order struct {
>	SenderSms   message.Message `singleton:"github.com/photowey/helloioc/internal/sms.Sender"`
>	SenderEmail message.Message `singleton:"github.com/photowey/helloioc/internal/email.Sender"`
>}
>```
>```go
>// +ioc:autowire=true
>// +ioc:autowire:type=singleton
>
>type Payment struct {
>	OrderAliasField    *order.Order `singleton:"order"`
>	OrderFullNameField *order.Order `singleton:"github.com/photowey/helloioc/internal/order.Order"`
>}
>```
>
>


`#3`

> When we need to perform dependency injection, it is recommended to consider using alias, if alias have been designed. This avoids bean names becoming verbose.



`#4`

> This proposal implementation may affect existing extensions, such as: gorm, grpc. But this time, I didn't make any changes, for fear that it would affect its normal workflow.

**Comment by photowey** [comment]
branch: `feature/issue19`

**Comment by photowey** [comment]
Thanks for your review and  suggestions, I think your suggestions are very reasonable, and I've fixed them now.

**Comment by photowey** [comment]
uts have basically passed

**Comment by photowey** [comment]
I think this proposal has been revised a lot, and we need to review it again and again.

**Comment by LaurenceLiZhixin** [comment]
OK, you can start a pr with [WIP]. @photowey

**Comment by photowey** [comment]
OK, the pr has been started, please see issue#20.
