### ISSUE TITLE
问：为什么生成方式选择了采用 wire 类似的编译时生成。而不是 go-spring 类似的运行时注入

### ISSUE THREAD

**Issue by sjsdfg** [alibaba/IOC-golang#38]
https://github.com/go-spring/go-spring

目前看起来当前项目的能力远远不够易用。
比如我们在 Java 里面使用的时候就有一个场景

我们希望把实现统一接口的  bean list 注入进来。
目前看当前接口是完全做不到的。

而且我们可能还需要有一些服务启动和结束的钩子给我们提供出来。目前也是没有看到的

**Comment by LaurenceLiZhixin** [comment]
1 java 有“实现特定接口”的概念，go没有这个概念，一个结构可以被注入任何接口，只要实现类方法。ioc-golang 是go 的ioc框架，不是spring 的go实现。
2 服务启动和结束的钩子，可以参考下example里面，结构的构造方法。
@sjsdfg

**Comment by sjsdfg** [comment]
关于第 2 点我这边展开说一下吧。

由于 go 是 duck 类型，所以 interface 和 struct 是若绑定的关系。
因此我理解，我们无法在运行时像 java 那样完全获取到这个 struct 实现哪些接口
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/8037152/174005230-06868df0-3219-4d11-b438-09d194b4ee3c.png">
go-spring 采用了这种注册以及回调的机制，可以告诉容器我实现了哪些接口。
因此可以被其他的 struct 进行 interface 的注入。

同时由于回调 Init 的方法。给与了 Java 的  `@PostConstructor` 的开发体验

**Comment by LaurenceLiZhixin** [comment]
@photowey Hi~, What do you think of this feature?

**Comment by LaurenceLiZhixin** [comment]
我认为如果需要使用这一能力，使用 go-spring 会更合适一些，ioc-golang 不计划支持这一能力。

**Comment by LaurenceLiZhixin** [comment]
之前我没有想清楚，非常抱歉。
我认为你说的非常对，这一能力很重要，我在日常开发的过程中也经常会用到这种模型。
go-spring 这块设计和实现的很不错。之前设计时并没有考虑这一模型，所以我近期尝试在ioc中增加这一自动装载模型，从而能够获取到接口的所有实现list，并与已有概念和架构结合起来。
非常感谢您提出的质疑和解释，欢迎多交流和批评指正。
@sjsdfg

**Comment by LaurenceLiZhixin** [comment]
例子更新至：https://github.com/alibaba/IOC-golang/blob/master/example/autowire/autowire_allimpls/main.go#L33
接口的所有实现都需要通过注解指定自动装载模型为：`allimpls`，即可通过字段注入、API 的方式获取接口全部实现。
```go
// +ioc:autowire=true
// +ioc:autowire:type=allimpls
// +ioc:autowire:allimpls:interface=github.com/alibaba/ioc-golang/example/autowire/autowire_allimpls/service.Service

type serviceImpl1 struct {
}

```

All impls could be injected to 

```go
// +ioc:autowire=true
// +ioc:autowire:type=singleton

type App struct {
	ServiceImpls []service.Service `allimpls:""`
}
```
