### ISSUE TITLE
[Proposal] Add built-in Logger interface

### ISSUE THREAD

**Issue by photowey** [alibaba/IOC-golang#39]
All log output must be taken over by Logger. If the developer does not provide an implementation, the built-in default log implementation is used.

**Comment by LaurenceLiZhixin** [comment]
@photowey  Thank you for your proposal. I think it is valuable and needs to be done at present.
For the Logger module, I think the framework needs to be developed from two perspectives.

1. Built-in Logger. We can provide a logger specially used for logging in the framework-level, that is, compared to current implementations, we should adding log level, file location and other basic information on the basis of retaining 'color'.
This logger can be defined by user.
We also need to define a interface like: 

```go
// Logger is the interface for Logger types
type Logger interface {
	Info(args ...interface{})
	Warn(args ...interface{})
	Error(args ...interface{})
	Debug(args ...interface{})
	Fatal(args ...interface{})

	Infof(fmt string, args ...interface{})
	Warnf(fmt string, args ...interface{})
	Errorf(fmt string, args ...interface{})
	Debugf(fmt string, args ...interface{})
	Fatalf(fmt string, args ...interface{})
}
```

I suppose this interface can be placed to `extension/normal/logger/logger.go`

2. User Logger under extension/normal/logger/impl/. Developers using the framework can inject logger implementation to this logger interface in their code to print app-level logs. The module needs to provide several preset implementation classes, like `extension/normal/logger/impl/console_logger` `extension/normal/logger/impl/file_logger` `extension/normal/logger/impl/elastic_logger `and so on. Each implementation should have special param and logic, for specific usage.
