### ISSUE TITLE
引用这个库需要引入一大堆依赖

### ISSUE THREAD

**Issue by hoozecn** [alibaba/IOC-golang#40]
https://github.com/alibaba/IOC-golang/blob/master/go.mod

我只想引入框架, 不想引入那一堆 extension 的实现. 

而且很可能依赖的版本和项目说用的版本不一致. 建议把 extension 的每个目录单独搞一个 go module, 想用的时候再引入单独的 module 即可.

**Comment by LaurenceLiZhixin** [comment]
@hoozecn  感谢你提出的问题。我可以明确地回答：**extension 中的实现只会在你需要使用的时候才会被引入。**

我们可以看 README 中给出的例子，我使用 go mod vendor 将全部依赖加载到目录下：

![image](https://user-images.githubusercontent.com/45508533/174275513-f083be53-598b-4a12-9b26-07bcd7994857.png)

这些依赖全部是框架基础依赖，并不涉及extension内的组件，例如 nacos。

你提到的项目根目录下的 go.mod 是项目视角的依赖，并不是用户真实加载的依赖。

版本控制是开发者需要考虑并解决的问题，引入 sub go module 可能会造成子模块和框架不兼容的情况。
