### ISSUE TITLE
[Proposal] Enhance config file load env variables.

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [alibaba/IOC-golang#55]
IOC-golang 配置文件加载方案

IOC-golang 框架配置文件格式为yaml格式，可以通过API的方式来制定配置加载。在本说明中，将给出配置加载的概念和规则。

### 1. 参数

**SearchPath**，[]string类型，表示配置搜索路径，会尝试搜索这些文件夹下的所有文件。

**ConfigType**，string类型，配置文件格式，目前支持 yaml、yml，默认yml

**ConfigName**，string类型，需要被加载的配置文件名称。

**Profile**，[]string 类型，需要被激活的配置文件后缀。如果在 API 中指定激活的 profile 为 “dev", ConfigName 为 "application", 则会从指定文件目录下加载 “application_dev.yaml" ，可同时加载多个profile，框架会对这些配置进行合并。

### 2. 参数加载方式

配置加载的参数可以通过 API 指定，也可以通过环境变量指定，API方式优先。

#### 2.1 API 方式指定参数

- config.WithSearchPath("./configs")

  指定需要搜索配置的文件夹路径，可指定多个

- config.WithConfigType("yaml")

  指定筛选出的配置文件类型，支持 yaml，yml，默认yml

- config.WithConfigName("app")

  指定需要加载的配置文件名

- config.WithProfilesActive("dev")

  指定激活的profile，可指定多个

例如：

```go
import(
	"github.com/alibaba/ioc-golang"
	"github.com/alibaba/ioc-golang/config"
)

func main(){
  if err := ioc.Load(
    config.WithSearchPath("./configs"),
    config.WithConfigType("yaml"),
    config.WithConfigName("app"),
    config.WithProfilesActive("dev")); err != nil {
		panic(err)
	}
}
```

将从./configs/文件夹下加载 app_dev.yaml 文件作为配置，基于这份配置启动框架。

### 2.2 环境变量指定参数

- export IOC_GOLANG_CONFIG_SEARCH_PATH="/home/root/app/config"

  指定需要搜索配置的文件夹绝对路径，使用',' 分割，可指定多个。

- export IOC_GOLANG_CONFIG_TYPE="yaml"

  指定筛选出的配置文件类型，支持 yaml，yml，默认yml

- export IOC_GOLANG_CONFIG_NAME="app"

  指定需要加载的配置文件名

- export IOC_GOLANG_CONFIG_ACTIVE_PROFILE="dev"

  指定激活的profile，可指定多个

环境变量指定的内容会被 API 覆盖。

### 3. 配置文件筛选逻辑示意图

![图片](https://user-images.githubusercontent.com/45508533/175305184-609ae47e-90a5-4297-87db-8349cc0a9a14.png)

### 4. 无配置文件启动

配置文件一般存放业务配置数据，框架启动不强依赖配置文件，配置文件加载失败会打印如下日志, 框架继续正常启动。

```bash
[Config] Load ioc-golang config file failed. open xxx/xxx/ioc_golang.yaml: no such file or directory
 The load procedure is continue
```

**Comment by LaurenceLiZhixin** [comment]
cc  @photowey

**Comment by photowey** [comment]
1.现在框架在加载配置文件时，确实还不支持通过环境变量来指定配置加载参数(2.2)；

- 接下来会尝试发起一次 `PR` 来增强。

2.由于框架本身默认的配置类型是 `yaml`。为了统一，接下来会将默认值由 `yml` 改为 `yaml`；

3.对于初始的环境变量`IOC_GOLANG_CONFIG_PATH` `IOC_GOLANG_ENV` 将继续支持，但不推荐;

- 推荐采用更为明确的方式，比如: `IOC_GOLANG_CONFIG_TYPE` `IOC_GOLANG_CONFIG_NAME`

**Comment by LaurenceLiZhixin** [comment]
@photowey 我同意你的观点，这个enhancement问题我已经开发的差不多了，我尽快把pr提上来。
IOC_GOLANG_CONFIG_PATH 和 IOC_GOLANG_ENV我打算删掉了。
新增上述四个环境变量。相关的ut我也会删掉。

**Comment by LaurenceLiZhixin** [comment]
The changes refers to https://github.com/alibaba/IOC-golang/pull/54/files#diff-64765abcc0f956f6f7bce36b2bfe7c11fb479525995b45852528cb55736445be
